### ISSUE TITLE
TCases Becomes extremly slow. 

### ISSUE THREAD

**Issue by hiteshmehata** [Cornutum/tcases#12]
I am trying use the tool and see all the possible combination that can be generated. But tool becomes extremely slow after I reach certain limit for the number of variable possibly.
I ran the tool for almost 7-8 hrs but it didn't complete the execution. Below the input XML and Generator file. 
I am using coverage level 3. 

Input XML:

```
<System name="cryptoAPI">
	<Function name="newKey">
		<Input type="platform">
			<Var name="platform">
				<Value name="iOS" property="iOS"/>
				<Value name="android"/>
				<Value name="Windows"/>
			</Var>
		</Input>
		<Input type="args">
			<Var name="algo">
				<Value name="securerandom"/>
				<Value name="random"/> 
				<Value name="passphrase"/>
				<Value name="invalid" property="invalidAlgo"/>
			</Var>
			<Var name="keyStrength">
				<Value name="128"/>
				<Value name="192"/>
				<Value name="256"/>
				<Value name="200" property="invalidKeyStrength"/>
			</Var>
			<VarSet name="propertyTable">
				<Var name="passphrasetext">
					<Value name="singalString" when="aes"/>
					<Value name="threeString" when="tripledes"/>
					<Value name="twoString" property="invalidPassPhrase"/>
				</Var>
				<Var name="subAlgo">
					<Value name="aes" property="aes"/>
					<Value name="tripledes" property="tripledes"/>
					<Value name="invalid" property="invalidAlgo"/>
				</Var>
				<Var name="passphrasehashlogo" when="iOS">
					<Value name="md2"/>
					<Value name="md4"/>
					<Value name="md5"/>
					<Value name="sha2"/>
				</Var>
			</VarSet>
		</Input>
		<Input type="vallidation">
			<Var name="response">
				<Value name="validString"/>
				<Value name="2001" when="invalidAlgo"/>
				<Value name="2002" when="invalidKeyStrength"/>
				<Value name="2005" when="invalidPassPhrase"/>
			</Var>
		</Input>
	</Function>
	<Function name="createHash">
		<Input type="args">
			<Var name="algo">
				<Value name="sha1" property="sha1"/>
				<Value name="sha224" property="sha224"/>
				<Value name="sha256" property="sha256"/>
				<Value name="sha384" property="sha384"/>
				<Value name="sha512" property="sha512"/>
				<Value name="md2" property="md2"/>
				<Value name="md4" property="md4"/>
				<Value name="md5" property="md5"/> 
				<Value name="invalid" property="invalidAlgo"/>
			</Var>
			<Var name="inputString">
				<Value name="shortString"/>
				<Value name="longString"/>
			</Var>
		</Input>
		<Input type="vallidation">
			<Var name="hexadecimalLength">
				<Value name="40" when="sha1"/>
				<Value name="56" when="sha224"/>
				<Value name="64" when="sha256"/>
				<Value name="96" when="sha384"/>
				<Value name="128" when="sha512"/>
				<Value name="32">
					<When>
						<AnyOf property="md2,md4,md5"/>
					</When>
				</Value>
				<Value name="2001" when="invalidAlgo"/>
			</Var>
		</Input>
	</Function>
	<Function name="createHMacHash">
		<Input type="platform">
			<Var name="platform">
				<Value name="iOS" property="iOS"/>
				<Value name="android"/>
				<Value name="Windows"/>
			</Var>
		</Input>
		<Input type="args">
			<Var name="algo">
				<Value name="sha1" property="sha1"/>
				<Value name="sha224" property="sha224"/>
				<Value name="sha256" property="sha256"/>
				<Value name="sha384" property="sha384"/>
				<Value name="sha512" property="sha512"/>
				<Value name="md2" property="md2"/>
				<Value name="md4" property="md4"/>
				<Value name="md5" property="md5"/> 
				<Value name="invalid" property="invalidAlgo"/>
			</Var>
			<Var name="message">
				<Value name="shortString"/>
				<Value name="longString"/>
			</Var>
		</Input>
		<Input type="key">
			<Var name="keyAlgo">
				<Value name="securerandom"/>
				<Value name="random"/> 
				<Value name="passphrase"/>
			</Var>
			<Var name="keyStrength">
				<Value name="128"/>
				<Value name="192"/>
				<Value name="256"/>
				<Value name="200" property="invalidKeyStrength"/>
			</Var>
			<VarSet name="propertyTable">
				<Var name="passphrasetext">
					<Value name="singalString" when="aes"/>
					<Value name="threeString" when="tripledes"/>
				</Var>
				<Var name="subAlgo">
					<Value name="aes" property="aes"/>
					<Value name="tripledes" property="tripledes"/>
					<Value name="empty" property="emptySubAlgo"/>
				</Var>
				<Var name="passphrasehashlogo" when="iOS">
					<Value name="md2"/>
					<Value name="md4"/>
					<Value name="md5"/>
					<Value name="sha2"/>
				</Var>
			</VarSet>
		</Input>
		<Input type="vallidation">
			<Var name="response">
				<Value name="105" when="emptySubAlgo"/>
				<Value name="104" when="invalidKeyStrength"/>
				<Value name="101" when="invalidAlgo"/>
				<Value name="validString"/>
			</Var>
		</Input>
	</Function>
	<Function name="encrypt">
		<Input type="platform">
			<Var name="platform">
				<Value name="iOS" property="iOS"/>
				<Value name="android"/>
				<Value name="windows" property="windows"/>
			</Var>
		</Input>
		<Input type="args">
			<Var name="algo">
				<Value name="aes" property="aes_algo"/>
				<Value name="tripledes" property="tripledes_algo"/>
				<Value name="rsa" property="rsa"/>
				<Value name="invalid" property="invalidAlgo"/>
			</Var>
			<Var name="inputString">
				<Value name="shortString"/>
				<Value name="longString"/>
				<Value name="empty" property="invalidInput"/>				
			</Var>
		</Input>
		<Input type="key">
			<VarSet name="generatedKey" whenNot="windows">
				<Var name="algo">
					<Value name="securerandom"/>
					<Value name="random"/> 
					<Value name="passphrase"/>
				</Var>
				<Var name="keyStrength">
					<Value name="128"/>
					<Value name="192"/>
					<Value name="256"/>
					<Value name="200" property="invalidKey"/>
				</Var>
				<VarSet name="propertyTable">
					<Var name="passphrasetext">
						<Value name="singalString" when="aes"/>
						<Value name="threeString" when="tripledes"/>
					</Var>
					<Var name="subAlgo">
						<Value name="aes" property="aes"/>
						<Value name="tripledes" property="tripledes"/>
						<Value name="empty" property="invalidKey"/>
					</Var>
					<Var name="passphrasehashlogo" when="iOS">
						<Value name="md2"/>
						<Value name="md4"/>
						<Value name="md5"/>
						<Value name="sha2"/>
					</Var>
				</VarSet>
			</VarSet>
			<VarSet name="generatedKeyW" when="windows">
				<Var name="algo">
					<Value name="rsa"/>
					<Value name="aes"/> 
					<Value name="invalid" property="invalidKey"/>
				</Var>
				<Var name="inputSource">
					<Value name="lccalCertPath"/>
					<Value name="invalidPath" property="invalidKey"/>
					<Value name="remoteCertPath" when="remote"/>
				</Var>
				<Var name="isLocalResource">
					<Value name="true"/>
					<Value name="false" property="remote"/>
					<Value name="default"/>
				</Var>
			</VarSet>
		</Input>
		<Input type="vallidation">
			<Var name="response">
				<Value name="2005" when="invalidInput"/>
				<Value name="2002" when="invalidKey"/>
				<Value name="2001" when="invalidAlgo"/>
				<Value name="validString" property="validString"/>
			</Var>
			<Var name="decryption" when="validString">
				<Value name="inputString"/>
			</Var>
		</Input>
	</Function>
	<Function name="saveKey">
		<Input type="platform">
			<Var name="platform">
				<Value name="iOS" property="iOS"/>
				<Value name="android"/>
				<Value name="windows" property="windows"/>
			</Var>
		</Input>
		<Input type="args">
			<Var name="uniqueID">
				<Value name="validString"/>
				<Value name="empty" property="empty"/>
				<Value name="duplicateString" property="duplicateString"/>
			</Var>
		</Input>
		<Input type="key">
			<VarSet name="generatedKey" whenNot="windows">
				<Var name="algo">
					<Value name="securerandom"/>
					<Value name="random"/> 
					<Value name="passphrase"/>
				</Var>
				<Var name="keyStrength">
					<Value name="128"/>
					<Value name="192"/>
					<Value name="256"/>
					<Value name="200" property="invalidKey"/>
				</Var>
				<VarSet name="propertyTable">
					<Var name="passphrasetext">
						<Value name="singalString" when="aes"/>
						<Value name="threeString" when="tripledes"/>
					</Var>
					<Var name="subAlgo">
						<Value name="aes" property="aes"/>
						<Value name="tripledes" property="tripledes"/>
						<Value name="empty" property="invalidKey"/>
					</Var>
					<Var name="passphrasehashlogo" when="iOS">
						<Value name="md2"/>
						<Value name="md4"/>
						<Value name="md5"/>
						<Value name="sha2"/>
					</Var>
				</VarSet>
			</VarSet>
			<VarSet name="generatedKeyW" when="windows">
				<Var name="algo">
					<Value name="rsa"/>
					<Value name="aes"/> 
					<Value name="invalid" property="invalidKey"/>
				</Var>
				<Var name="inputSource">
					<Value name="lccalCertPath"/>
					<Value name="invalidPath" property="invalidKey"/>
					<Value name="remoteCertPath" when="remote"/>
				</Var>
				<Var name="isLocalResource">
					<Value name="true"/>
					<Value name="false" property="remote"/>
					<Value name="default"/>
				</Var>
			</VarSet>
		</Input>
		<Input type="vallidation">
			<Var name="response">
				<Value name="2006" when="duplicateString" property="keyNotSaved"/>
				<Value name="2004" when="empty" property="keyNotSaved"/>
				<Value name="validID" property="validID"/>
			</Var>
			<VarSet name="readKey">
				<Var name="keyName">
					<Value name="uniqueID" when="validID"/>
					<Value name="nonExistingID" property="nonExistingID" when="keyNotSaved"/>
				</Var>
				<Var name="response">
					<Value name="2007" when="nonExistingID"/>
					<Value name="validString"/>
				</Var>
			</VarSet> 
			<VarSet name="deleteKey">
				<Var name="keyName">
					<Value name="uniqueID" when="validID"/>
					<Value name="nonExistingID" property="nonExistingID" when="keyNotSaved"/>
				</Var>
				<Var name="response">
					<Value name="2007" when="nonExistingID"/>
					<Value name="validString"/>
				</Var>
			</VarSet> 
		</Input>
	</Function>
</System>
```

Generator XML:
```
<?xml version="1.0"?>
<Generators>
  <TupleGenerator function="*" tuples="3">
  </TupleGenerator>
</Generators>
```

**Comment by kerrykimbrough** [comment]
For a quick check, try generating for the default coverage (tuples=1). One easy way to do this is to run Tcases like this:

```tcases < myInputModelFile``` 

For example, when I do this on your input model, I see the following error, which indicates [a problem with constraints](http://www.cornutum.org/tcases/docs/Tcases-Guide.htm#conditionTips) on subAlgo=empty
```
java.lang.RuntimeException: FunctionInputDef[createHMacHash]: Can't create test cases
	at org.cornutum.tcases.generator.TupleGenerator.getTests(TupleGenerator.java:178)
	at org.cornutum.tcases.Tcases.getTests(Tcases.java:1224)
	at org.cornutum.tcases.Tcases.run(Tcases.java:1091)
	at org.cornutum.tcases.Tcases.main(Tcases.java:896)
Caused by: java.lang.RuntimeException: Can't create test case for tuple=Tuple[[subAlgo=empty]]
	at org.cornutum.tcases.generator.TupleGenerator.createTestCase(TupleGenerator.java:403)
	at org.cornutum.tcases.generator.TupleGenerator.getValidCases(TupleGenerator.java:348)
	at org.cornutum.tcases.generator.TupleGenerator.getTests(TupleGenerator.java:149)
	... 3 more
```

**Comment by hiteshmehata** [comment]
Hi Kerry,

Thanks for the tip. But I am still not able to understand what exactly is the problem here. I soon as I remove the "empty" value for the "subAlgo" it doesn't through any error and output gets generated. But I am not able to add any third value with or without constraint for the "subAlgo" var. Below is the smaller XML with the problem:
```<System name="cryptoAPI">
    <Function name="createHMacHash">
        <Input type="platform">
            <Var name="platform">
                <Value name="iOS" property="iOS"/>
                <Value name="android"/>
                <Value name="Windows"/>
            </Var>
        </Input>
        <Input type="args">
            <Var name="algo">
                <Value name="sha1" property="sha1"/>
                <Value name="sha224" property="sha224"/>
                <Value name="sha256" property="sha256"/>
                <Value name="sha384" property="sha384"/>
                <Value name="sha512" property="sha512"/>
                <Value name="md2" property="md2"/>
                <Value name="md4" property="md4"/>
                <Value name="md5" property="md5"/> 
                <Value name="invalid" property="invalidAlgo"/>
            </Var>
            <Var name="message">
                <Value name="shortString"/>
                <Value name="longString"/>
            </Var>
        </Input>
        <Input type="key">
            <Var name="keyAlgo">
                <Value name="securerandom"/>
                <Value name="random"/> 
                <Value name="passphrase"/>
            </Var>
            <Var name="keyStrength">
                <Value name="128"/>
                <Value name="192"/>
                <Value name="256"/>
                <Value name="200" property="invalidKeyStrength"/>
            </Var>
            <VarSet name="propertyTable">
                <Var name="passphrasetext">
                    <Value name="singalString" when="aes"/>
                    <Value name="threeString" when="tripledes"/>
                </Var>
                <Var name="subAlgo">
                    <Value name="aes" property="aes"/>
                    <Value name="tripledes" property="tripledes"/>
		    **_ <Value name="empty" property="subAlgoEmpty"/>_**
                </Var>
                <Var name="passphrasehashlogo" when="iOS">
                    <Value name="md2"/>
                    <Value name="md4"/>
                    <Value name="md5"/>
                    <Value name="sha2"/>
                </Var>
            </VarSet>
        </Input>
        <Input type="vallidation">
            <Var name="response">
                <Value name="105" when="subAlgoEmpty"/>
                <Value name="104" when="invalidKeyStrength"/>
                <Value name="101" when="invalidAlgo"/>
                <Value name="validString"/>
            </Var>
        </Input>
    </Function>
</System>```

**Comment by kerrykimbrough** [comment]
Perhaps you have noticed already: the cause of the problem is Var= passphrasetext. None of its values are compatible with subAlgo=empty.

**Comment by kerrykimbrough** [comment]
Perhaps you have noticed already: the cause of the problem is Var= passphrasetext. None of its values are compatible with subAlgo=empty.

**Comment by hiteshmehata** [comment]
Thank Kerry.
